{{- if .Values.graphql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superbapp.fullname" . }}-graphql
spec:
  type: {{ .Values.graphql.service.type }}
  selector:
{{/*    app: {{ include "superbapp.labels" . }}*/}}
    app: superbapp-graphql
    component: graphql
    release: {{ .Release.Name }}
  ports:
    - name: graphql
      protocol: TCP
      port: {{ .Values.graphql.service.externalPort }}
      {{- if and (eq .Values.graphql.service.type "NodePort") (.Values.graphql.service.nodePort.http) }}
      nodePort: {{ .Values.graphql.service.nodePort.http }}
      {{- end }}
      targetPort: 3000
  {{- if eq .Values.graphql.service.type "LoadBalancer" }}
  {{- if .Values.graphql.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.graphql.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if .Values.graphql.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.graphql.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
