---
# Source: superbapp/templates/auth/auth-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: superbapp-chart-auth
spec:
  type: ClusterIP
  selector:

    app: superbapp-auth
    component: auth
    release: RELEASE-NAME
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
