---
# Source: superbapp/templates/graphql/graphql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superbapp-chart-graphql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      ## multiple graphql pods can safely run concurrently
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: superbapp-graphql
      component: graphql
      release: RELEASE-NAME

  template:
    metadata:
      labels:
        app: superbapp-graphql
        component: graphql
        release: RELEASE-NAME
    spec:
      restartPolicy: Always
      containers:
        - name: superbapp-graphql
          imagePullPolicy: IfNotPresent
          ports:
            - name: graphql-grpc
              containerPort: 3000
              hostPort: 4200
              protocol: TCP
          image: taptap21/superbapp-graphql:latest
          env:
            - name: BOOKING_SERVICE_URI
              value: 'RELEASE-NAME-booking.superb.svc.cluster.local'
            - name: AUTH_SERVICE_URI
              value: 'RELEASE-NAME-auth.superb.svc.cluster.local'

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            exec:
              command:
                - "ash"
                - "-c"
                - "wget --no-verbose --tries=1 --spider http://localhost:3000/healthz"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            exec:
              command:
                - "ash"
                - "-c"
                - "wget --no-verbose --tries=1 --spider http://localhost:3000/healthz"
