{{- if and (.Values.client.enabled) (.Values.client.ingress.enabled)}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "superbapp.fullname" . }}-client
  {{- if .Values.client.ingress.annotations }}
  annotations:
    {{- toYaml .Values.client.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: superbapp-client
    component: client
    release: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.client.ingress.host }}
      http:
        paths:
          - path: {{ .Values.client.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "superbapp.fullname" . }}-client
                port:
                  name: client
{{- end }}
