---
# Source: superbapp/templates/client/client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superbapp-chart-client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      ## multiple client pods can safely run concurrently
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: superbapp-client
      component: client
      release: RELEASE-NAME

  template:
    metadata:
      labels:
        app: superbapp-client
        component: client
        release: RELEASE-NAME
    spec:
      restartPolicy: Always
      containers:
        - name: superbapp-client
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 80
              hostPort: 4300
              protocol: TCP
          image: "taptap21/superbapp-client:0.3"

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            exec:
              command:
                - "ash"
                - "-c"
                - "wget --no-verbose --tries=1 --spider http://localhost:80"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            exec:
              command:
                - "ash"
                - "-c"
                - "wget --no-verbose --tries=1 --spider http://localhost:80"
