name: auth-production-build

on:
  push:
    branches: [ main ]
#    paths:
#      - src/auth/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/auth

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: taptap21/superbapp-auth
          flavor: |
            latest=auto
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: src/auth
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


