name: frontend-production-build

on:
  push:
    branches: [ main ]
    paths:
      - src/client/**
      - content/resource_graph/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - name: Setup node with caching
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: src/client/package-lock.json

      - name: Install npm dependencies
        run: npm install

      - name: Build static files
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Upload to S3
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET}}
        run: |
          aws s3 sync build/ $AWS_BUCKET/ --delete

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2.0.2
#        env:
#          SITE_NAME: frontend.wernichbekker.com
#          HOST_NAME: Production
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Invalidate Cloudfront
        env:
          AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: taptap21/superbapp-client
          flavor: |
            latest=auto
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: src
          file: src/client/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
