name: frontend-production-build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - name: Setup node with caching
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Build static files
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Upload US to S3
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET}}
        run: |
          aws s3 sync build/ $AWS_BUCKET/ --delete

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2.0.2
#        env:
#          SITE_NAME: frontend.wernichbekker.com
#          HOST_NAME: Production
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Invalidate Cloudfront
        env:
          AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"
