name: booking-production-build

on:
  push:
    branches: [ main ]
    paths:
      - src/booking/**
      - src/proto/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v2

      - name: Setup node with caching
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: src/auth/package-lock.json

      - name: Install npm dependencies
        run: npm install

      - name: Build static files
        run: |
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: taptap21/superbapp-auth

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: booking/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2.0.2
#        env:
#          SITE_NAME: frontend.wernichbekker.com
#          HOST_NAME: Production
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

